### ISSUE TITLE
Double Images

### ISSUE THREAD

**Issue by dargmuesli** [m-kyle/SpotBright#2]
Hey @m-kyle,

thanks for merging my PR. I open this issue referencing [my comment](https://github.com/m-kyle/SpotBright/pull/1#issuecomment-303589724) which addressed the problem of multiple wallpapers having the same name because they show the same landscape but at different times or perspectives. In your [last commit](https://github.com/m-kyle/SpotBright/commit/be72e9595630388df425e2b5d0f1f8107b6085da) you updated one image.

My question is: How can we decide which image to keep?  
You [said](https://github.com/m-kyle/SpotBright/pull/1#issuecomment-303644699) that the image "Mesa Arch, Utah" was renamed to `240066343561386151image_fullscreen_001_landscape.jpg`. Where does this name come from, do you have an idea?

I've searched for similar images and found some duplicates with the same naming issue. Shall we keep the ones with simple names or the complicated ones?  
For example `211498612678102017evergreen_offset_28663_500kb_1080x1920.jpg`a and `Chattooga River 1080x1920.jpg`.

**Comment by m-kyle** [comment]
Originally I only had one Mesa Arch image, but at some point a second one was added when I got more images from SpotBright. There was an update sometime ago to SpotBright which changed the way some images were named, using a more descriptive name like `Chattooga River 1080x1920.jpg`, which I assume is coming from the metadata in the image.

**Comment by dargmuesli** [comment]
Ok, let me list all current duplicates:

## 1080x1920
  - `211498612678102017evergreen_offset_28663_500kb_1080x1920.jpg`
    - `Chattooga River 1080x1920.jpg`
  - `211498603938258278evergreen_65790253_500kb_1080x1920.jpg`
    - `Giant's Causeway Ireland 1080x1920.jpg`
  - `211498553804664906evergreen_27097855_500kb_1080x1920.jpg`
    - `Jellyfish 1080x1920.jpg`
  - `240066350996463240image_fullscreen_001_portrait.jpg`
    - `Mesa Arch, Utah 1080x1920.jpg`
  - `211508628713819619evergreen_73287641_500kb_1080x1920.jpg`
    - `Milky Way Galaxy 1080x1920.jpg`
  - `211519993295459014evergreen_65002895_500kb_1080x1920.jpg`
    - `Montenegro 1080x1920.jpg`
  - `211555168355060326evergreen_offset_161383_500kb_1080x1920.jpg`
    - `Perito Moreno, Argentina 1080x1920.jpg`
  - `240066412103367453image_fullscreen_001_portrait.jpg`
    - `Cornwall, England 1080x1920.jpg`
  - `211512778596573471evergreen_77388617_500kb_1080x1920.jpg`
    - `Kiama, Australia 1080x1920.jpg`
  - `211497075477023091evergreen_offset_171853_500kb_1080x1920.jpg`
    - `Greenland 1080x1920.jpg`
  - `211549215953082954evergreen_95962867_500kb_1080x1920.jpg`
    - `St. Joseph, Michigan 1080x1920.jpg`
  - `211512786235661163evergreen_66045845_500kb_1080x1920.jpg`
    - `Monte Aloia, Spain 1080x1920.jpg`
  - `211508625862604585evergreen_80728231_500kb_1080x1920.jpg`
    - `Torres del Paine, Chile 1080x1920.jpg`
  - `211498561351009061evergreen_46301424_500kb_1080x1920.jpg`
    - `Noirmoutier, France 1080x1920.jpg`
  - `211512786006022943evergreen_58460480_500kb_1080x1920.jpg`
    - `Zingst, Germany 1080x1920.jpg`
  - `211498613621467791evergreen_offset_88143_500kb_1080x1920.jpg`
    - `Hokkaido Island, Japan 1080x1920.jpg`

## 1920x1080
  - `211498600447213294evergreen_65790253_500kb_1920x1080.jpg`
    - `Giant's Causeway Ireland 1920x1080.jpg`
  - `211498540767686842evergreen_27097855_500kb_1920x1080.jpg`
    - `Jellyfish 1920x1080.jpg`
  - `211508619845654714evergreen_73287641_500kb_1920x1080.jpg`
    - `Milky Way Galaxy 1920x1080.jpg`
  - `211512774440747340evergreen_66045845_500kb_1920x1080.jpg`
    - `Monte Aloia, Spain 1920x1080.jpg`
  - `211555160926816806evergreen_offset_161383_500kb_1920x1080.jpg`
    - `Perito Moreno, Argentina 1920x1080.jpg`
  - `211512777843133685evergreen_58460480_500kb_1920x1080.jpg`
    - `Zingst, Germany 1920x1080.jpg`
  - `211519988747130507evergreen_65002895_500kb_1920x1080.jpg`
    - `Montenegro 1920x1080.jpg`
  - `240066378794011847image_fullscreen_001_landscape.jpg`
    - `Khao Phing Kan, Thailand 1920x1080.jpg`
  - `211549212216632064evergreen_95962867_500kb_1920x1080.jpg`
    - `St. Joseph, Michigan 1920x1080.jpg`
  - `211508620513216494evergreen_80728231_500kb_1920x1080.jpg`
    - `Torres del Paine, Chile 1920x1080.jpg`
  - `240066394083994305image_fullscreen_001_landscape.jpg`
    - `Lavender in Bulgaria 1920x1080.jpg`
  - `240066407215623523image_fullscreen_001_landscape.jpg`
    - `Cornwall, England 1920x1080.jpg`
  - `211512773200442259evergreen_77388617_500kb_1920x1080.jpg`
    - `Kiama, Australia 1920x1080.jpg`
  - `211498540698655376evergreen_57050222_500kb_1920x1080.jpg`
    - `Moraine Lake, Canada 1920x1080.jpg`
  - `240066374238416331image_fullscreen_001_landscape.jpg`
    - `Seljalandsfoss, Iceland 1920x1080.jpg`
  - `211497071844438352evergreen_offset_171853_500kb_1920x1080.jpg`
    - `Greenland 1920x1080.jpg`
  - `211498600989098595evergreen_offset_88143_500kb_1920x1080.jpg`
    - `Hokkaido Island, Japan 1920x1080.jpg`

Both lists do *not* contain the same images, but they are similar.

On my side I've three images in both resolutions that SpotBright downloaded into a new folder:

- `Big Sur, California`
- `Mesa Arch, Utah` (you already fixed this one for 1920x1080)
- `Namib Desert, Africa`
- `Tuscany, Italy`

There are already files with the same name in this repo's folder.

**Comment by m-kyle** [comment]
I have removed the duplicate images. I decided to keep the descriptive names for the images, as they were generally a slightly larger file.

For the images which end in `fullscreen_001_landscape.jpg`, I have renamed them the same as the descriptive ones (as they are a much larger file) and removed the descriptive named images.

**Comment by dargmuesli** [comment]
Ok, now what shall we do with [the other duplicates](https://github.com/Dargmuesli/spotbright/commit/8162db3caa642daf3ed44eea59e5c7fb9eeb1588) SpotBright downloaded into another folder?

**Comment by m-kyle** [comment]
I guess we could rename one of the duplicate images with a number a the end:
`Big Sur, California 1080x1920.jpg` -> `Big Sur, California 2 1080x1920.jpg`.

I don't really see any good option other than that.
